# PyChamberFlux user settings
# comply with YAML(TM) 1.1 standard <http://yaml.org/spec/1.1/>
# use PyYAML <http://pyyaml.org/> to parse into Python.
# Note: please modify the user config only, not the default config.


run_options:
    save_fitting_plots: false
    
    save_daily_plots: false


data_dir:
    biomet_data: "./test/input/biomet/*.dat"

    conc_data: "./test/input/conc/*.str"
    
    output_dir: "./test/output/"

    output_filename_str: "sr"

    plot_dir: "./test/plots/"

    separate_conc_data: true


biomet_data_settings:
    delimiter: ','
    
    header: 4

    names: ['timestamp','T_log','ch_no', 'T_ch_1', 'T_ch_2', 'T_ch_3',
            'T_ch_4', 'T_ch_5', 'T_ch_6', 'T_atm', 'RH_atm',
            'PAR_ch_1', 'PAR_ch_2', 'PAR_ch_3', 'PAR_ch_4',
            'flow_ch_1', 'flow_ch_2', 'flow_ch_3', 'flow_ch_4',
            'flow_ch_5', 'flow_ch_6', 'flow_7',
            'T_soil_ch_4', 'w_soil_ch_4', 'T_soil_ch_5', 'w_soil_ch_5',
            'T_soil_ch_6', 'w_soil_ch_6']

    usecols: [0, 2, 4, 5, 7, 9, 11, 13, 15, 18, 23, 28, 33, 38, 43, 48, 53, 
              58, 63, 68, 73, 78, 82, 84, 93, 95, 104, 106]

    na_values: "\"NAN\""


conc_data_settings:
    delimiter: "\\s+"

    header: 1

    names: ['time_sec', 'cos', 'co2', 'h2o', 'co2_2']


site_parameters:
    site_pressure: 96.8e+3
    
    time_zone: -7


species_settings:
    species_list: ['cos', 'co2', 'h2o']
    
    species_names: ['COS', 'CO$_2$', 'H$_2$O']
